[tool.poetry]
name = "meetup-katas"
version = "0.1.0"
description = ""
authors = ["GuiMcs00 <guilherme.amaral2004@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^8.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
